# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 18) do

  create_table "item_images", :force => true do |t|
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "size",         :integer
    t.column "item_id",      :integer
    t.column "thumbnail",    :string
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "title",        :string
    t.column "extra",        :string
    t.column "position",     :string
    t.column "created_on",   :datetime
    t.column "parent_id",    :integer
    t.column "listpos",      :integer
  end

  create_table "items", :force => true do |t|
    t.column "title",          :string
    t.column "content",        :string,   :limit => 4096
    t.column "time_period_id", :integer
    t.column "category",       :string
    t.column "subcategory",    :string
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
    t.column "item_image_id",  :integer
    t.column "extra",          :string
    t.column "link",           :string
    t.column "position",       :string
  end

  create_table "service_offers", :force => true do |t|
    t.column "type",          :text
    t.column "content",       :text,    :default => "", :null => false
    t.column "item_image_id", :integer
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

end
